#! /bin/sh

bspc monitor HDMI-0 -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio           0.60
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

xrandr --output HDMI-0 --mode 1920x1080 --rate 75 &

picom -b --experimental-backends &

~/.fehbg &

~/.config/polybar/launch.sh &

sxhkd &

mpd &

xsetroot -cursor_name left_ptr
